services:
  bongard:
    image: llava
    stdin_open: true # docker run -i
    tty: true # docker run -t
    command: tail -f /dev/null
    ports:
      - "3333:3333"
    volumes:
      - '../:/workspace'
    working_dir: /workspace
    deploy:
      resources:
        limits:
          cpus: '50'
          memory: 500g
        reservations:
          devices:
            - driver: nvidia
              device_ids: [ '4' ]
              capabilities: [ gpu ]
